apiVersion: v1
kind: Secret
metadata:
  name: cloud-config
  namespace: kube-system
  annotations:
    helm.sh/hook: pre-install
data:
  cloud.conf: {{.Values.cloudconf}}
  cacert: {{.Values.cacert}}
