changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Documentation 📝
      labels:
        - documentation
    - title: Denpendencies 🔄
      labels:
        - dependencies
    - title: Bugs 🐛
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"