# permissions for end users to view observers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observer-viewer-role
rules:
- apiGroups:
  - app.undistro.io
  resources:
  - observers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.undistro.io
  resources:
  - observers/status
  verbs:
  - get
