---
apiVersion: app.undistro.io/v1alpha1
kind: HelmRelease
metadata:
  name: nginx
  namespace: undistro-system
spec:
  targetNamespace: ingress-nginx
  # clusterName in <namespace/name> format
  clusterName: undistro-system/management
  chart:
    repository: https://registry.undistro.io/chartrepo/library
    name: ingress-nginx
    version: 4.0.6
  autoUpgrade: true
  values:
    podLabels:
      network.undistro.io/ingress: allow
      network.undistro.io/egress: allow
---
apiVersion: app.undistro.io/v1alpha1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: undistro-system
spec:
  clusterName: undistro-system/management
  dependencies:
    - apiVersion: app.undistro.io/v1alpha1
      kind: HelmRelease
      name: nginx
      namespace: undistro-system
  chart:
    repository: https://kubernetes.github.io/dashboard
    name: kubernetes-dashboard
    version: 4.0.0
  autoUpgrade: true
  afterApplyObjects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: dashboard-access
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: undistro-quickstart-dash
          namespace: undistro-system
  values:
    podLabels:
      network.undistro.io/ingress: allow
      network.undistro.io/egress: allow
    ingress:
      enabled: true
    serviceAccount:
      name: undistro-quickstart-dash
