{{- with .Values.credentials }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
  name: undistro-azure-config
  namespace: undistro-system
  annotations:
    helm.sh/hook: pre-install
data:
  clientID: {{ .clientID | b64enc }}
  clientSecret: {{ .clientSecret | b64enc }}
  subscriptionID: {{ .subscriptionID | b64enc }}
  tenantID: {{ .tenantId | b64enc }}
type: Opaque
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: "dfault"
  namespace: undistro-system
spec:
  allowedNamespaces: {}
  clientID:  {{ .clientID }}
  clientSecret:
    name: undistro-azure-config
    namespace: undistro-system
  tenantID: {{ .tenantID }}
  type: ServicePrincipal
{{- end }}
