---
apiVersion: app.undistro.io/v1alpha1
kind: HelmRelease
metadata:
  annotations:
    security.undistro.io/kyverno: ""
  name: "kyverno-{{.Cluster.Name}}"
  namespace: "{{.Cluster.Namespace}}"
spec:
  {{if and (ne .Cluster.Namespace "undistro-system") (ne .Cluster.Name "management")}}
  clusterName: "{{.Cluster.Namespace}}/{{.Cluster.Name}}"
  {{end}}
  releaseName: kyverno
  targetNamespace: kyverno
  chart:
    repository: "https://registry.undistro.io/chartrepo/library"
    name: kyverno
    version: 1.4.2
  values:
    {{if .Cluster.HasInfraNodes}}
    nodeSelector:
      node-role.undistro.io/infra: 'true'
    tolerations:
      - effect: 'NoSchedule'          
        key: 'dedicated'              
        value: 'infra'   
    {{end}}
    fullnameOverride: kyverno
    namespace: kyverno
    resources:                 
      limits:                  
        memory: 2Gi            
        cpu: 2000m             
      requests:                
        cpu: 500m              
        memory: 500Mi
