{{- with .Values.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: undistro-openstack-config
  namespace: undistro-system
  annotations:
    helm.sh/hook: pre-install
data:
  {{if .caFile}}
  caFile: {{ .caFile }}
  {{end}}
  dnsNameServers: {{ .dnsNameServers | b64enc}}
{{- end}}
